### ISSUE TITLE
[JOSS] `protocol` version when installing from source vs install through pip 

### ISSUE THREAD

**Issue by htwangtw** [Open-Minds-Lab/MRdataset#24]
openjournals/joss-reviews#6269

* MRdataset version: 0.1.dev
* Python version: 3.10.12
* Operating System: Ubuntu 22.04.3 LTS

### Description

This is part of the JOSS submission review.

In the installation instruction, the stable release will install a key dependency `protocol` version 0.3, however if we strictly follow the install from source instruction, it will be 0.1. 

These two things should be consistent.

### What I Did
```
virtualenv env-stable
source env-stable/bin/activate
pip install -U MRdataset
pip list
```
From source:
```
git clone git://github.com/Open-Minds-Lab/MRdataset
cd MRdataset
virtualenv env
source env/bin/activate
pip install git+https://github.com/sinhaharsh/protocol.git#egg=protocol
pip install -r requirements_dev.txt
pip install -e .
pip list
```

**Comment by raamana** [comment]
that's a great catch Hao, thank you. I guess we never attempted install from source :)

we will update the docs to make it they should use `pip install -U MRdataset` when possible, and only when they trying to contribute as a developer should they use the other instructions.

I personally don't understand the parameter `#egg=protocol` in this command
in `pip install git+https://github.com/sinhaharsh/protocol.git#egg=protocol`
but my guess is we don't need it. @sinhaharsh and I take a look and fix the docs asap.

**Comment by sinhaharsh** [comment]
Compiling protocol from source was initially required. It's surely not required anymore. It is now addressed in the documentation. Thank you Hao.

**Comment by sinhaharsh** [comment]
The installation instructions are now updated. Installing MRdataset will also install latest protocol from PyPI

**Comment by htwangtw** [comment]
LGTM!
