### ISSUE TITLE
[JOSS] Jupyter notebook linked in documentation is outdated

### ISSUE THREAD

**Issue by htwangtw** [Open-Minds-Lab/MRdataset#26]
openjournals/joss-reviews#6269

The tutorial notebook doesn't match the `usage.ipynb` file in the repository.
The online version also includes function that's not present in the current version of the library (such as `print_tree`)

**Comment by sinhaharsh** [comment]
Thanks Hao. I have updated the notebook [link](https://nbviewer.org/github/Open-Minds-Lab/MRdataset/blob/main/docs/usage.ipynb) in the documentation.
