### ISSUE TITLE
[JOSS] terms in Figure 2

### ISSUE THREAD

**Issue by djmannion** [Open-Minds-Lab/MRdataset#31]
https://github.com/openjournals/joss-reviews/issues/6269

In Figure 2, the 'vertical traversal' is shown as varying in 'SITE' but described as "across multiple sequences for a given subject". Maybe I am just misinterpreting, but should 'SITE' be 'SEQUENCE'?

**Comment by sinhaharsh** [comment]
Regarding Figure 2, the vertical traversal shown is across sequences, namely T1w, DWI, fMRI, T2w. The purpose of this figure is to demonstrate that each site uses a specific acquisition protocol for collecting MR scans. This protocol contains several sequences, each of which has multiple parameters. The panels in the figure represent the interface that appears on the scanner during acquisition.

It's important to note that the direction for the site should be in the Z-direction (which is into the page). As you can see from the figure, the front panels display SITE 1, while the back panels display SITE 2.

However, the direction for the site has been omitted for the sake of brevity. I hope this clarifies things for you. Please let me know if you require any additional information. I can add the direction for site if you think it would be helpful.

**Comment by djmannion** [comment]
Thanks for the explanation - I had interpreted the panels as the vertical traversal (like how the panels are the horizontal traversal), not the sequences within each panel. Maybe the 'vertical traversal' arrow could start at the top the T1w box and end at the bottom of the T2w box rather than encompassing all the panels. I'll leave it to your judgement.

**Comment by raamana** [comment]
thanks Damien - you're not wrong in interpreting that way - given we were too close to the project, we didn't see that confusion can arise. We will revise the figure to be more unambiguous and self-explanatory
